CREATE TYPE icon_size as ENUM {
  'small', 'medium', 'large'
};
CREATE TYPE icon_shape as ENUM {
  'square', 'rounded', 'circle'
};
CREATE TYPE alignment as ENUM {
  'left', 'center', 'null'
}

CREATE TABLE users (
  id Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now(),

  enable_pages BOOLEAN NOT NULL DEFAULT FALSE,
  enable_folders BOOLEAN NOT NULL DEFAULT TRUE,
  enable_groups BOOLEAN NOT NULL DEFAULT FALSE,
  enable_hiding BOOLEAN NOT NULL DEFAULT FALSE,
  icon_size icon_size NOT NULL default 'medium',
  icon_shape icon_shape NOT NULL default 'rounded',
  per_row INTEGER NOT NULL DEFAULT 5,
);
