CREATE TABLE bookmark_images (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  base_url TEXT NOT NULL,
  bytes INTEGER,
  width INTEGER,
  height INTEGER,
  image_url TEXT NOT NULL,
  image_format TEXT
);
